#!/usr/bin/env python3
"""Rebuild portfolio_data.py from the deployed dashboard (deploy/index.html).

The dashboard embeds all portfolio data as one-line JS constants:
    const NAME = <json>;
This script parses those constants and writes portfolio_data.py so a fresh
session can always reconstruct the workspace from the GitHub Pages repo.

Usage:  python3 extract_data.py [path/to/index.html]
"""
import json, re, sys, pprint

CONSTS = ["ASOF", "GROUPS", "STOCKS", "POS", "TRADES", "SELLPLAN", "CASH",
          "REALIZED", "TOTALS", "SOLD", "MONTHLY", "THBFX", "M3"]

def extract(html_path):
    html = open(html_path, encoding="utf-8").read()
    data = {}
    for name in CONSTS:
        m = re.search(r"^const %s = (.*);$" % name, html, re.M)
        if not m:
            raise SystemExit(f"ERROR: const {name} not found in {html_path}")
        data[name] = json.loads(m.group(1))
    return data

def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "deploy/index.html"
    data = extract(src)
    pp = pprint.PrettyPrinter(width=120, sort_dicts=False)
    with open("portfolio_data.py", "w", encoding="utf-8") as f:
        f.write('"""Pillar-4 US portfolio data — generated by extract_data.py from %s.\n' % src)
        f.write('Edit values here, then run gen_dashboard.py to regenerate the dashboard.\n')
        f.write('Do NOT change ticker/name/ex/g or POS (positions) during fundamentals refreshes.\n"""\n\n')
        for name in CONSTS:
            f.write(f"{name} = {pp.pformat(data[name])}\n\n")
        f.write("METRICS3 = M3  # alias: per-ticker pfcf / ev (EV/EBITDA) / de (Debt/Equity)\n\n")
        f.write("def rows():\n    return STOCKS\n")
    print(f"portfolio_data.py written: {len(data['STOCKS'])} stocks, as of {data['ASOF']!r}")

if __name__ == "__main__":
    main()
